global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'devops-monitoring'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'python_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus-nginxlog-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-nginxlog-exporter:4040']

  - job_name: 'nginx-prometheus-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
