version: '3.8'
services:
  alertmanager_1:
    image: prom/alertmanager:latest
    container_name: alertmanager_1
    ports:
      - "9082:9082"
    volumes:
      - ../../config/alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--data.retention=48h'
      - '--log.level=debug'
      - '--cluster.listen-address=0.0.0.0:9083'
      - '--web.listen-address=0.0.0.0:9082'
  alertmanager_2:
    image: prom/alertmanager:latest
    container_name: alertmanager_2
    ports:
      - "9084:9084"
    volumes:
      - ../../config/alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--data.retention=48h'
      - '--log.level=debug'
      - '--cluster.listen-address=0.0.0.0:9085'
      - '--cluster.peer=alertmanager_1:9083'
      - '--web.listen-address=0.0.0.0:9084'

networks:
  default:
    external:
      name: monitoring